<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p> ID especialidade : <?php echo $especialidade-> getID() ?> </p>
    <p> Designação : <?php echo $especialidade-> getDesignacao() ?> </p>
</body>
</html>